[package]
name = "oxyflow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
mac_address = "1.1.5"
opentelemetry = { version = "0.21.0", features = ["metrics"] }
pcap = "1.1.0"
